#!/usr/bin/env bash
#script that displays Best School 10 times using while loop with disturbance on 9th line
count=1
while [ "$count" -le 10 ]
do
echo "Best School"
if [ "$count" -eq 9 ]
then
echo "Hi"
fi
count=$((count + 1))
done
