#!/usr/bin/env bash
# This script creates a PID file and handles signals

pid_file="/var/run/myscript.pid"

echo $$ > "$pid_file"

handle_sigterm() {
    echo "I hate the kill command"
    rm -f "$pid_file"
    exit
}

handle_sigint() {
    echo "Y U no love me?!"
}

handle_sigquit() {
    rm -f "$pid_file"
    exit
}

trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
